# Generated by Django 5.2.14 on 2026-05-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_seriedocumental_subseriedocumental_tipodocumental'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.seriedocumental'),
        ),
        migrations.AddField(
            model_name='document',
            name='subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.subseriedocumental'),
        ),
        migrations.AddField(
            model_name='document',
            name='tipo_documental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.tipodocumental'),
        ),
    ]
