# Generated by Django 5.2.15 on 2026-07-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_tvdseccion_tvdserie_tvdsubserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tvd_subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.tvdsubserie', verbose_name='subserie TVD'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tvd_subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='documents.tvdsubserie', verbose_name='subserie TVD'),
        ),
        migrations.AddField(
            model_name='seriedocumental',
            name='retencion_archivo_central',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='archivo central'),
        ),
        migrations.AddField(
            model_name='seriedocumental',
            name='retencion_archivo_gestion',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='archivo de gestion'),
        ),
        migrations.CreateModel(
            name='TipoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_required', models.BooleanField(default=False, verbose_name='requerido')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('subserie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='documents.subseriedocumental', verbose_name='subserie')),
            ],
            options={
                'verbose_name': 'tipo documental',
                'verbose_name_plural': 'tipos documentales',
                'ordering': ['subserie__serie__dependencia__code', 'subserie__serie__code', 'subserie__code', 'name'],
                'unique_together': {('subserie', 'name')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tipo_documental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.tipodocumental', verbose_name='tipo documental'),
        ),
    ]
