# Generated by Django 5.2.14 on 2026-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_asunto_document_fecha_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estado',
            field=models.CharField(choices=[('radicado', 'Radicado'), ('en_tramite', 'En tramite'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='radicado', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='soporte',
            field=models.CharField(choices=[('fisico', 'Fisico'), ('digital', 'Digital'), ('hibrido', 'Hibrido')], default='digital', max_length=20),
        ),
    ]
