# Generated by Django 5.2.14 on 2026-05-06 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_estado_document_soporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='estado',
            field=models.CharField(choices=[('radicado', 'Radicado'), ('en_tramite', 'En tramite'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], db_index=True, default='radicado', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='fecha_radicacion',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='numero_radicado',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='soporte',
            field=models.CharField(choices=[('fisico', 'Fisico'), ('digital', 'Digital'), ('hibrido', 'Hibrido')], db_index=True, default='digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=180),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dependencia', 'fecha_radicacion'], name='documents_d_depende_672bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dependencia', 'estado'], name='documents_d_depende_d3f2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dependencia', 'created_at'], name='documents_d_depende_6a13a9_idx'),
        ),
    ]
