# Generated by Django 5.2.15 on 2026-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_tvd_subserie_expediente_tvd_subserie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodocumental',
            table='documents_tipo_documental',
        ),
    ]
