# Generated by Django 5.2.14 on 2026-05-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_serie_document_subserie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subseriedocumental',
            name='final_disposition',
        ),
        migrations.AddField(
            model_name='subseriedocumental',
            name='disposition_ct',
            field=models.BooleanField(default=False, verbose_name='conservacion total'),
        ),
        migrations.AddField(
            model_name='subseriedocumental',
            name='disposition_d',
            field=models.BooleanField(default=False, verbose_name='digitalizacion'),
        ),
        migrations.AddField(
            model_name='subseriedocumental',
            name='disposition_e',
            field=models.BooleanField(default=False, verbose_name='eliminacion'),
        ),
        migrations.AddField(
            model_name='subseriedocumental',
            name='disposition_s',
            field=models.BooleanField(default=False, verbose_name='seleccion'),
        ),
    ]
