# Generated by Django 5.2.14 on 2026-06-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=60)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], db_index=True, default='abierto', max_length=20)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to=settings.AUTH_USER_MODEL)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='documents.dependencia')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='documents.seriedocumental')),
                ('subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='documents.subseriedocumental')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.expediente'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['dependencia', 'estado'], name='documents_e_depende_e596c1_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['dependencia', 'created_at'], name='documents_e_depende_9fb786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('dependencia', 'codigo')},
        ),
    ]
