# Generated by Django 5.2.14 on 2026-06-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_expediente_document_expediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tipo_documental',
        ),
        migrations.DeleteModel(
            name='TipoDocumental',
        ),
    ]
