# Generated by Django 5.2.14 on 2026-07-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_tipodocumental_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodocumental',
            table=None,
        ),
    ]
