# Generated by Django 5.2.14 on 2026-05-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_dependencia_document_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='documents.dependencia')),
            ],
            options={
                'verbose_name': 'serie documental',
                'verbose_name_plural': 'series documentales',
                'ordering': ['dependencia__code', 'code', 'name'],
                'unique_together': {('dependencia', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SubserieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('retention_management', models.PositiveSmallIntegerField(default=0, verbose_name='archivo de gestion')),
                ('retention_central', models.PositiveSmallIntegerField(default=0, verbose_name='archivo central')),
                ('final_disposition', models.CharField(blank=True, choices=[('CT', 'Conservacion total'), ('E', 'Eliminacion'), ('D', 'Digitalizacion'), ('S', 'Seleccion')], max_length=2)),
                ('procedures', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subseries', to='documents.seriedocumental')),
            ],
            options={
                'verbose_name': 'subserie documental',
                'verbose_name_plural': 'subseries documentales',
                'ordering': ['serie__dependencia__code', 'serie__code', 'code', 'name'],
                'unique_together': {('serie', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TipoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subserie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='documents.subseriedocumental')),
            ],
            options={
                'verbose_name': 'tipo documental',
                'verbose_name_plural': 'tipos documentales',
                'ordering': ['subserie__serie__dependencia__code', 'subserie__serie__code', 'subserie__code', 'name'],
                'unique_together': {('subserie', 'name')},
            },
        ),
    ]
