# Generated by Django 5.2.14 on 2026-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_subseriedocumental_final_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='asunto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fecha_radicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
