# Generated by Django 5.2.14 on 2026-06-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_document_tipo_documental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVDSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'sección TVD',
                'verbose_name_plural': 'secciones TVD',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TVDSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='codigo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='documents.tvdseccion', verbose_name='sección')),
            ],
            options={
                'verbose_name': 'serie TVD',
                'verbose_name_plural': 'series TVD',
                'ordering': ['seccion__code', 'code', 'name'],
                'unique_together': {('seccion', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TVDSubserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='codigo')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('retention_management', models.PositiveSmallIntegerField(default=0, verbose_name='archivo de gestion (años)')),
                ('retention_central', models.PositiveSmallIntegerField(default=0, verbose_name='archivo central (años)')),
                ('disposition_ct', models.BooleanField(default=False, verbose_name='conservacion total (CT)')),
                ('disposition_e', models.BooleanField(default=False, verbose_name='eliminacion (E)')),
                ('disposition_d', models.BooleanField(default=False, verbose_name='digitalizacion (D)')),
                ('disposition_s', models.BooleanField(default=False, verbose_name='seleccion (S)')),
                ('procedures', models.TextField(blank=True, verbose_name='procedimientos')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subseries', to='documents.tvdserie', verbose_name='serie')),
            ],
            options={
                'verbose_name': 'subserie TVD',
                'verbose_name_plural': 'subseries TVD',
                'ordering': ['serie__seccion__code', 'serie__code', 'code', 'name'],
                'unique_together': {('serie', 'code')},
            },
        ),
    ]
