# Generated by Django 5.2.14 on 2026-06-06 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0010_remove_document_tipo_documental_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento fallido de inicio'), ('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('VIEW', 'Consulta'), ('DOWNLOAD', 'Descarga / Previsualización'), ('EXPORT', 'Exportación de datos')], db_index=True, max_length=30)),
                ('module', models.CharField(choices=[('AUTH', 'Autenticación'), ('DOCUMENTOS', 'Documentos'), ('EXPEDIENTES', 'Expedientes'), ('TRD', 'Estructura TRD'), ('SISTEMA', 'Sistema')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.dependencia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['dependencia', 'timestamp'], name='audit_audit_depende_cfa63b_idx'), models.Index(fields=['module', 'action', 'timestamp'], name='audit_audit_module_029fcf_idx')],
            },
        ),
    ]
