# Generated by Django 5.2.15 on 2026-07-10 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('documents', '0012_document_tvd_subserie_expediente_tvd_subserie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-fecha'], 'verbose_name': 'registro de auditoría', 'verbose_name_plural': 'registros de auditoría'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_e8be02_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_depende_cfa63b_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_module_029fcf_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'fecha'], name='audit_audit_user_id_8581be_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['dependencia', 'fecha'], name='audit_audit_depende_7e1156_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'action', 'fecha'], name='audit_audit_module_70156e_idx'),
        ),
    ]
